// MB64 overlay/section registration. The section/overlay tables are generated by
// N64Recomp into recomp_overlays.inl; this just hands them to librecomp so it can
// resolve function-pointer / overlay jumps at runtime.
// overlays.hpp (and the macOS SDK <string> it pulls in) MUST come before the
// recomp .inl: recomp.h defines macros that otherwise poison the SDK's strchr
// const-overloads ("functions that differ only in return type").
#include "librecomp/overlays.hpp"
#include "../RecompiledFuncs/recomp_overlays.inl"

#ifndef ARRLEN
#define ARRLEN(x) (sizeof(x) / sizeof((x)[0]))
#endif

namespace mb64 {
    void register_overlays();
    void register_resident_function_addresses(uint8_t* rdram, recomp_context* ctx);
}

void mb64::register_overlays() {
    recomp::overlays::overlay_section_table_data_t sections {
        .code_sections = section_table,
        .num_code_sections = ARRLEN(section_table),
        .total_num_sections = num_sections,
    };

    recomp::overlays::overlays_by_index_t overlays {
        .table = overlay_sections_by_index,
        .len = ARRLEN(overlay_sections_by_index),
    };

    recomp::overlays::register_overlays(sections, overlays);
}

// Register every resident function at its natural linked address.
//
// librecomp's init() loads the resident code with ONE linear load_overlays()
// call (rom 0x1000 -> entrypoint, 1MB), which assumes a single constant rom->ram
// offset. That holds for the first section (section_4 "main" @ 0x80124330) but
// NOT for SM64's later sections (e.g. section_6 "engine" @ 0x8014C2E0, which sits
// at a different offset), so their functions land in the lookup table at the
// wrong vram and every indirect call into them — thread entries, the game loop —
// fails get_function() and aborts. Re-register each function at section.ram_addr
// + func.offset (its real linked address) so the lookup succeeds. Wired in as the
// GameEntry on_init_callback, so it runs right after init() and before the
// recompiled entrypoint.
// libultra's static sprintf output callback (see mb64_ultra_stubs.cpp). It has no
// symbol in the prebuilt libnustd, so N64Recomp folded it into sprintf() and gave
// it no lookup entry; sprintf() -> _Printf() calls it indirectly and would abort
// ("Failed to find function at 0x80132358"). Register our reimplementation here.
extern "C" void proutSprintf_recomp(uint8_t* rdram, recomp_context* ctx);
static constexpr int32_t kProutSprintfAddr = (int32_t)0x80132358;

void mb64::register_resident_function_addresses(uint8_t* /*rdram*/, recomp_context* /*ctx*/) {
    for (size_t s = 0; s < ARRLEN(section_table); s++) {
        const SectionTableEntry& section = section_table[s];
        for (size_t f = 0; f < section.num_funcs; f++) {
            const FuncEntry& fe = section.funcs[f];
            recomp::overlays::add_loaded_function((int32_t)(section.ram_addr + fe.offset), fe.func);
        }
    }
    recomp::overlays::add_loaded_function(kProutSprintfAddr, proutSprintf_recomp);
}
