// Audio output for the Mario Builder 64 macOS port.
//
// The recompiled aspMain RSP audio microcode (rsp/aspMain.cpp, generated by
// RSPRecomp) synthesizes 16-bit stereo samples into RDRAM; the game's audio
// thread hands them to queue_samples() via ultramodern's audio callbacks. Here
// we convert/resample to the host device's rate and push them to SDL.
//
// Adapted from the recomp template's main.cpp audio path, minus the Zelda
// main-volume hook (we use full volume) and its throw/exit error handling.

#include <array>
#include <cstdio>
#include <vector>
#include <algorithm>

#include "SDL2/SDL.h"

#include "mb64_audio.h"

namespace {
    SDL_AudioCVT audio_convert;
    SDL_AudioDeviceID audio_device = 0;

    // Samples per channel per second.
    uint32_t sample_rate = 48000;        // game (input) rate; set by set_frequency
    uint32_t output_sample_rate = 48000; // host device rate
    constexpr uint32_t input_channels = 2;
    uint32_t output_channels = 2;

    // A frame = one sample per channel. Frames duplicated to fix interpolation
    // at chunk boundaries.
    constexpr uint32_t duplicated_input_frames = 4;
    uint32_t discarded_output_frames = 0;
    constexpr uint32_t bytes_per_frame = input_channels * sizeof(float);

    void update_audio_converter() {
        int ret = SDL_BuildAudioCVT(&audio_convert, AUDIO_F32, input_channels, sample_rate,
                                    AUDIO_F32, output_channels, output_sample_rate);
        if (ret < 0) {
            fprintf(stderr, "[audio] SDL_BuildAudioCVT failed: %s\n", SDL_GetError());
            return;
        }
        discarded_output_frames = duplicated_input_frames * output_sample_rate / sample_rate;
    }
}

void mb64::audio::reset(uint32_t output_freq) {
    SDL_AudioSpec spec_desired{};
    spec_desired.freq = (int)output_freq;
    spec_desired.format = AUDIO_F32;
    spec_desired.channels = (Uint8)output_channels;
    spec_desired.samples = 0x100; // small buffer for low latency
    spec_desired.callback = nullptr;

    audio_device = SDL_OpenAudioDevice(nullptr, false, &spec_desired, nullptr, 0);
    if (audio_device == 0) {
        fprintf(stderr, "[audio] SDL_OpenAudioDevice failed: %s (continuing silent)\n", SDL_GetError());
        return;
    }
    SDL_PauseAudioDevice(audio_device, 0);

    output_sample_rate = output_freq;
    update_audio_converter();
}

void mb64::audio::queue_samples(int16_t* audio_data, size_t sample_count) {
    if (audio_device == 0) {
        return;
    }
    static std::vector<float> swap_buffer;
    static std::array<float, duplicated_input_frames * input_channels> duplicated_sample_buffer{};

    size_t resampled_sample_count = sample_count + duplicated_input_frames * input_channels;
    size_t max_sample_count = std::max(resampled_sample_count,
                                       resampled_sample_count * (size_t)audio_convert.len_mult);
    if (max_sample_count > swap_buffer.size()) {
        swap_buffer.resize(max_sample_count);
    }

    // Prepend the duplicated frames carried over from the previous chunk.
    for (size_t i = 0; i < duplicated_input_frames * input_channels; i++) {
        swap_buffer[i] = duplicated_sample_buffer[i];
    }

    // 16-bit -> float, swapping L/R to undo the endianness address xor. Full volume.
    constexpr float kScale = 0.5f / 32768.0f;
    for (size_t i = 0; i < sample_count; i += input_channels) {
        swap_buffer[i + 0 + duplicated_input_frames * input_channels] = audio_data[i + 1] * kScale;
        swap_buffer[i + 1 + duplicated_input_frames * input_channels] = audio_data[i + 0] * kScale;
    }

    if (sample_count <= duplicated_input_frames * input_channels) {
        return; // too small to resample with duplicated frames
    }

    // Stash the trailing converted samples for the next chunk.
    for (size_t i = 0; i < duplicated_input_frames * input_channels; i++) {
        duplicated_sample_buffer[i] = swap_buffer[i + sample_count];
    }

    audio_convert.buf = reinterpret_cast<Uint8*>(swap_buffer.data());
    audio_convert.len = (int)((sample_count + duplicated_input_frames * input_channels) * sizeof(swap_buffer[0]));

    if (SDL_ConvertAudio(&audio_convert) < 0) {
        fprintf(stderr, "[audio] SDL_ConvertAudio failed: %s\n", SDL_GetError());
        return;
    }

    uint64_t cur_queued_microseconds =
        uint64_t(SDL_GetQueuedAudioSize(audio_device)) / bytes_per_frame * 1000000 / sample_rate;
    uint32_t num_bytes_to_queue =
        audio_convert.len_cvt - output_channels * discarded_output_frames * sizeof(swap_buffer[0]);
    float* samples_to_queue = swap_buffer.data() + output_channels * discarded_output_frames / 2;

    // Drop samples if too much is already buffered, to bound latency.
    uint32_t skip_factor = (uint32_t)(cur_queued_microseconds / 100000);
    if (skip_factor != 0) {
        uint32_t skip_ratio = 1u << skip_factor;
        num_bytes_to_queue /= skip_ratio;
        for (size_t i = 0; i < num_bytes_to_queue / (output_channels * sizeof(swap_buffer[0])); i++) {
            samples_to_queue[2 * i + 0] = samples_to_queue[2 * skip_ratio * i + 0];
            samples_to_queue[2 * i + 1] = samples_to_queue[2 * skip_ratio * i + 1];
        }
    }

    SDL_QueueAudio(audio_device, samples_to_queue, num_bytes_to_queue);
}

size_t mb64::audio::get_frames_remaining() {
    if (audio_device == 0) {
        return 0;
    }
    constexpr float buffer_offset_frames = 1.0f;
    uint64_t buffered_byte_count = SDL_GetQueuedAudioSize(audio_device);
    buffered_byte_count = buffered_byte_count * 2 * sample_rate / output_sample_rate / output_channels;

    uint32_t frames_per_vi = (sample_rate / 60);
    if (buffered_byte_count > (uint64_t)(buffer_offset_frames * bytes_per_frame * frames_per_vi)) {
        buffered_byte_count -= (uint64_t)(buffer_offset_frames * bytes_per_frame * frames_per_vi);
    } else {
        buffered_byte_count = 0;
    }
    return static_cast<size_t>(buffered_byte_count / bytes_per_frame);
}

void mb64::audio::set_frequency(uint32_t freq) {
    sample_rate = freq;
    update_audio_converter();
}
